// CSS is linked directly in index.html (render-blocking, avoids a flash of unstyled content),
// so only the theme's scripts need runtime injection here.
//
// Paths are root-relative so the app still works when deployed under a subpath (e.g.
// /frontend/); the map below prepends BASE_URL to each one at load time.
const RAW_JS_SRCS: string[] = [
  "https://maps.googleapis.com/maps/api/js?key=AIzaSyDduF2tLXicDEPDMAtC6-NLOekX0A5vlnY",
  "/html/assets/vendor_assets/js/jquery/jquery-3.5.1.min.js",
  "/html/assets/vendor_assets/js/jquery/jquery-ui.js",
  "/html/assets/vendor_assets/js/bootstrap/popper.js",
  "/html/assets/vendor_assets/js/bootstrap/bootstrap.min.js",
  "/html/assets/vendor_assets/js/moment/moment.min.js",
  "/html/assets/vendor_assets/js/Chart.min.js",
  "/html/assets/vendor_assets/js/accordion.js",
  "/html/assets/vendor_assets/js/autoComplete.js",
  "/html/assets/vendor_assets/js/charts.js",
  "/html/assets/vendor_assets/js/daterangepicker.js",
  "/html/assets/vendor_assets/js/drawer.js",
  "/html/assets/vendor_assets/js/dynamicBadge.js",
  "/html/assets/vendor_assets/js/dynamicCheckbox.js",
  "/html/assets/vendor_assets/js/feather.min.js",
  "/html/assets/vendor_assets/js/footable.min.js",
  "/html/assets/vendor_assets/js/fullcalendar@5.2.0.js",
  "/html/assets/vendor_assets/js/google-chart.js",
  "/html/assets/vendor_assets/js/jquery-jvectormap-2.0.5.min.js",
  "/html/assets/vendor_assets/js/jquery-jvectormap-world-mill-en.js",
  "/html/assets/vendor_assets/js/jquery.countdown.min.js",
  "/html/assets/vendor_assets/js/jquery.filterizr.min.js",
  "/html/assets/vendor_assets/js/jquery.mCustomScrollbar.min.js",
  "/html/assets/vendor_assets/js/jquery.magnific-popup.min.js",
  "/html/assets/vendor_assets/js/jquery.peity.min.js",
  "/html/assets/vendor_assets/js/jquery.star-rating-svg.min.js",
  "/html/assets/vendor_assets/js/leaflet.js",
  "/html/assets/vendor_assets/js/leaflet.markercluster.js",
  "/html/assets/vendor_assets/js/loader.js",
  "/html/assets/vendor_assets/js/message.js",
  "/html/assets/vendor_assets/js/moment.js",
  "/html/assets/vendor_assets/js/muuri.min.js",
  "/html/assets/vendor_assets/js/notification.js",
  "/html/assets/vendor_assets/js/popover.js",
  "/html/assets/vendor_assets/js/select2.full.min.js",
  "/html/assets/vendor_assets/js/slick.min.js",
  "/html/assets/vendor_assets/js/trumbowyg.min.js",
  "/html/assets/vendor_assets/js/wickedpicker.min.js",
  "/html/assets/theme_assets/js/drag-drop.js",
  "/html/assets/theme_assets/js/footable.js",
  "/html/assets/theme_assets/js/full-calendar.js",
  "/html/assets/theme_assets/js/googlemap-init.js",
  "/html/assets/theme_assets/js/icon-loader.js",
  "/html/assets/theme_assets/js/jvectormap-init.js",
  "/html/assets/theme_assets/js/leaflet-init.js",
  "/html/assets/theme_assets/js/main.js"
]

export const DASHBOARD_JS_SRCS: string[] = RAW_JS_SRCS.map((src) =>
  src.startsWith('/') ? `${import.meta.env.BASE_URL}${src.slice(1)}` : src,
)
